import os
from dotenv import load_dotenv

load_dotenv()
api_key = os.getenv("HF_TOKEN")

from langchain.chains import LLMChain
from langchain_core.prompts import PromptTemplate
from langchain_huggingface import HuggingFaceEndpoint

class ResearchAssistant:
    def __init__(self, api_key, model="Qwen/QwQ-32B", max_length=512, temperature=0.7):
        self.api_key = api_key
        self.llm = HuggingFaceEndpoint(
            repo_id=model,
            max_length=max_length,
            temperature=temperature,
            huggingfacehub_api_token=api_key
        )
        self.prompt_template = PromptTemplate.from_template(self._get_template())

    def _get_template(self):
        return """You are an AI assistant specializing in research. Analyze the given topic carefully and provide a well-structured response.

        Topic: {topic}

        Introduction:
        Provide a brief overview of the topic and its significance.

        Background Information:
        Explain the historical and theoretical context relevant to this topic.

        Key Findings and Research Data:
        Summarize the most important discoveries, studies, or relevant data points related to the topic.

        Critical Analysis:
        Evaluate different perspectives, advantages, limitations, and any debates surrounding this topic.

        Conclusion and Future Directions:
        Summarize the key takeaways and suggest possible future research directions or applications.

        NOTE: ALL THE WORDINGS AND THE GENERATION TITLE INTRODUCTION OR GENERATED BY YOUR OWN WITHOUT USING THE LINE BREAK
        Response:
        """

    def generate_response(self, topic):
        llm_chain = LLMChain(llm=self.llm, prompt=self.prompt_template)
        return llm_chain.invoke({"topic": topic})

# Example Usage
if __name__ == "__main__":
    assistant = ResearchAssistant(api_key)
    topic = "The impact of AI on climate change research"
    response = assistant.generate_response(topic)
    print("************************************")
    print(response)
